//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainSetting
    {
        public int idMainSetting { get; set; }
        public string Name { get; set; }
        public string sValue { get; set; }
        public Nullable<int> iValue { get; set; }
        public Nullable<System.DateTime> dValue { get; set; }
    }
}
