//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int idUser { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> isLogin { get; set; }
        public Nullable<bool> isInvoicing { get; set; }
    }
}
