//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItems
    {
        public int idInvoiceItem { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceVat { get; set; }
        public Nullable<double> PriceFull { get; set; }
        public Nullable<int> idBaseValue { get; set; }
        public Nullable<double> Count { get; set; }
        public Nullable<double> BasePrice { get; set; }
        public Nullable<double> BaseVat { get; set; }
        public Nullable<double> BasePriceFull { get; set; }
    }
}
