//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanPDFs
    {
        public int idScan { get; set; }
        public Nullable<int> idInvoice { get; set; }
        public Nullable<int> idJobs { get; set; }
        public Nullable<int> ScanIncrement { get; set; }
    }
}
