//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public int idSupplier { get; set; }
        public string Name { get; set; }
        public string Ic { get; set; }
        public string Dic { get; set; }
        public string Adresa { get; set; }
        public string Psc { get; set; }
        public string Mesto { get; set; }
        public Nullable<bool> IsNespolehlivyPlatce { get; set; }
    }
}
