//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class alextradeEntities : DbContext
    {
        public alextradeEntities()
            : base("name=alextradeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FirmCategory> FirmCategory { get; set; }
        public virtual DbSet<Firms> Firms { get; set; }
        public virtual DbSet<InvoiceItems> InvoiceItems { get; set; }
        public virtual DbSet<Invoices> Invoices { get; set; }
        public virtual DbSet<InvoiceState> InvoiceState { get; set; }
        public virtual DbSet<MainSetting> MainSetting { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderState> OrderState { get; set; }
        public virtual DbSet<Pair> Pair { get; set; }
        public virtual DbSet<PairType> PairType { get; set; }
        public virtual DbSet<SazbaDPH> SazbaDPH { get; set; }
        public virtual DbSet<ScanPDFs> ScanPDFs { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Unity> Unity { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserSetting> UserSetting { get; set; }
        public virtual DbSet<DayPrices> DayPrices { get; set; }
        public virtual DbSet<Druh> Druh { get; set; }
        public virtual DbSet<Komodita> Komodita { get; set; }
        public virtual DbSet<ListedCompany> ListedCompany { get; set; }
        public virtual DbSet<PodKomodita> PodKomodita { get; set; }
        public virtual DbSet<Priznak> Priznak { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<InvoiceItemState> InvoiceItemState { get; set; }
        public virtual DbSet<ListedProduct> ListedProduct { get; set; }
        public virtual DbSet<wFirms> wFirms { get; set; }
        public virtual DbSet<wInvoices> wInvoices { get; set; }
        public virtual DbSet<wItems> wItems { get; set; }
        public virtual DbSet<wOrders> wOrders { get; set; }
        public virtual DbSet<wPair> wPair { get; set; }
        public virtual DbSet<wScanPDFs> wScanPDFs { get; set; }
        public virtual DbSet<wProductTable> wProductTable { get; set; }
        public virtual DbSet<wWeekMinPricesTemp> wWeekMinPricesTemp { get; set; }
        public virtual DbSet<wWeekPrices> wWeekPrices { get; set; }
        public virtual DbSet<wWeekPricesTemp> wWeekPricesTemp { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    }
}
