//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayPrices
    {
        public int idDayPrices { get; set; }
        public int idProduct { get; set; }
        public int idListedCompany { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> DatePrice { get; set; }
        public Nullable<int> WeekPrice { get; set; }
        public Nullable<int> MonthPrice { get; set; }
        public Nullable<int> YearPrice { get; set; }
        public Nullable<int> DayPrice { get; set; }
    }
}
