//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmCategory
    {
        public int idFirmCategory { get; set; }
        public string Category { get; set; }
        public Nullable<int> idMainFirmCategory { get; set; }
    }
}
