//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int idHistory { get; set; }
        public Nullable<int> Poradi { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Text { get; set; }
        public Nullable<int> Doba { get; set; }
    }
}
