//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int idInvoice { get; set; }
        public Nullable<int> idOrder { get; set; }
        public Nullable<int> idFirm { get; set; }
        public Nullable<int> MyNumber { get; set; }
        public string HisNumber { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Vat { get; set; }
        public Nullable<double> PriceFull { get; set; }
        public Nullable<int> NrItems { get; set; }
        public Nullable<System.DateTime> DateDUZP { get; set; }
    }
}
