//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceState
    {
        public int idInvoiceState { get; set; }
        public Nullable<int> idInvoice { get; set; }
        public Nullable<int> StateValue { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<int> idUser { get; set; }
    }
}
