//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pair
    {
        public int idPair { get; set; }
        public Nullable<int> idInvoiceItem { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<System.DateTime> DatePairPrice { get; set; }
        public Nullable<double> PairPrice { get; set; }
        public Nullable<int> idPairType { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<System.DateTime> DatePairing { get; set; }
        public Nullable<int> PairWeek { get; set; }
    }
}
