//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int idProduct { get; set; }
        public Nullable<int> idKomodita { get; set; }
        public Nullable<int> idPodkomodita { get; set; }
        public Nullable<int> idPriznak { get; set; }
        public string Product1 { get; set; }
        public string Mark { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> idUnit { get; set; }
    }
}
