//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class SazbaDPH
    {
        public int idSazbaDPH { get; set; }
        public Nullable<double> SazbaDPH1 { get; set; }
        public string SazbaDPHText { get; set; }
        public string SazbaDPHTextShort { get; set; }
    }
}
