//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int idState { get; set; }
        public Nullable<int> StateType { get; set; }
        public Nullable<int> StateValue { get; set; }
        public string StateTypeDescription { get; set; }
        public string StateValueDescription { get; set; }
        public string StateValueInfo { get; set; }
    }
}
