//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class wFirms
    {
        public int idFirm { get; set; }
        public string Name { get; set; }
        public string Ic { get; set; }
        public string Dic { get; set; }
        public string Adress { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public Nullable<int> idFirmCategory { get; set; }
        public string Category { get; set; }
    }
}
