//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class wOrders
    {
        public string Ic { get; set; }
        public string Dic { get; set; }
        public string Adress { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public int idOrder { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> idFirm { get; set; }
        public string SCANPath { get; set; }
        public Nullable<int> NrSCAN { get; set; }
        public Nullable<int> NrInvoices { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserFullName { get; set; }
        public string OrderName { get; set; }
        public string FirmName { get; set; }
        public Nullable<int> MaxStateValue { get; set; }
        public string StateValueDescription { get; set; }
        public string SCANPrefix { get; set; }
        public Nullable<int> CountInvoices { get; set; }
        public Nullable<int> ExpectedItems { get; set; }
        public Nullable<double> ExpectedPrice { get; set; }
        public Nullable<int> CountItems { get; set; }
        public Nullable<double> PriceItems { get; set; }
    }
}
