//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class wProductTable
    {
        public string Druh { get; set; }
        public string Komodita { get; set; }
        public string Podkomodita { get; set; }
        public int idProduct { get; set; }
        public string Product { get; set; }
        public string Priznak { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Mark { get; set; }
        public string UnitShort { get; set; }
        public string UnitName { get; set; }
        public int idUnit { get; set; }
        public Nullable<int> idKomodita { get; set; }
        public Nullable<int> idPriznak { get; set; }
        public Nullable<int> idDruh { get; set; }
        public Nullable<int> idPodkomodita { get; set; }
    }
}
