//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class wScanPDFs
    {
        public int idScan { get; set; }
        public Nullable<int> idInvoice { get; set; }
        public Nullable<int> idOrder { get; set; }
        public Nullable<int> ScanIncrement { get; set; }
        public Nullable<int> MyNumber { get; set; }
        public string HisNumber { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> NrItems { get; set; }
        public Nullable<System.DateTime> DateDUZP { get; set; }
        public string FirmName { get; set; }
    }
}
