//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing
{
    using System;
    using System.Collections.Generic;
    
    public partial class wWeekPrices
    {
        public int idProduct { get; set; }
        public Nullable<double> C42 { get; set; }
        public Nullable<double> C43 { get; set; }
        public Nullable<double> C44 { get; set; }
        public Nullable<double> C45 { get; set; }
        public Nullable<double> C46 { get; set; }
        public Nullable<double> C47 { get; set; }
        public Nullable<double> C48 { get; set; }
        public Nullable<double> C49 { get; set; }
        public Nullable<double> C50 { get; set; }
    }
}
